package proyectoFinal.modelo.dominio;
import java.util.Random;
public class FrasesMotivacionales {
    private final String[] frases = {
            "El éxito es la suma de pequeños esfuerzos repetidos día tras día",
            "Lo que no te desafía, no te cambia",
            "El dolor que sientes hoy será la fuerza que sentirás mañana",
            "No cuentes los días, haz que los días cuenten",
            "Si te resulta fácil, no estás mejorando",
            "Cada gota de sudor acerca tu sueño",
            "La diferencia entre lo posible e imposible está en la determinación",
            "Cuando pienses en rendirte, recuerda por qué empezaste",
            "Un año más tarde desearías haber empezado hoy",
            "El esfuerzo no se traiciona",
            "Tu única limitación es la que estableces en tu mente",
            "No eres víctima de las circunstancias, eres creador de posibilidades",
            "El optimismo es el imán de los milagros",
            "Los ganadores encuentran formas, los perdedores excusas",
            "Tu actitud determina tu altitud",
            "No esperes el momento perfecto, toma el momento y hazlo perfecto",
            "Las crisis sacan a relucir lo mejor de los verdaderos guerreros",
            "El miedo es una brújula que señala lo que realmente importa",
            "Cada 'no' acerca más el 'sí' definitivo",
            "La energía fluye donde va la atención",
            "La mejor versión de ti mismo está esperando ser descubierta",
            "Hoy es el primer día del resto de tu vida",
            "Reinventarse es la forma más pura de libertad",
            "No compitas con otros, supera tu mejor versión",
            "Lo que no te mata, te hace más fuerte... y más sabio",
            "Los errores son lecciones disfrazadas",
            "Cada batalla perdida te enseña a ganar la guerra",
            "Tu potencial es como el océano: profundo e inexplorado",
            "El crecimiento duele, la mediocridad mata",
            "No naciste para ser ordinario",
            "Los sueños no funcionan a menos que tú lo hagas",
            "Detrás de cada 'de la noche a la mañana' hay años de dedicación",
            "El éxito es 1% inspiración y 99% transpiración",
            "Los campeones juegan hasta que se hace bien, no hasta que se cansen",
            "Nadie que dio su mejor esfuerzo se arrepintió después",
            "La disciplina es el puente entre metas y logros",
            "Las excusas son los clavos para construir la casa del fracaso",
            "El éxito no es final, el fracaso no es fatal: lo que cuenta es el coraje para continuar",
            "La grandeza requiere grandes sacrificios",
            "No hay ascensor al éxito, debes tomar las escaleras",
            "Tu cuerpo puede aguantar casi cualquier cosa, es tu mente la que debes convencer",
            "El hierro nunca miente: lo que levantas hoy, te levanta mañana",
            "El sudor es grasa llorando",
            "No importa si vas lento, sigues adelantando a todos los que están en el sofá",
            "Las agujetas son besos de tu progreso",
            "Entrena como si alguien estuviera hablando mal de ti",
            "Más fuerte no significa menos humano, significa más dedicación",
            "La primera repetición se hace con el cuerpo, la última con el alma",
            "No existe 'no puedo', existe 'aún no'",
            "Cada gota de sudor es tu pasado quemándose",
            "Las ideas no tienen horario: atápalas cuando lleguen",
            "La creatura favorita de la creatividad es la curiosidad",
            "Los locos que creen poder cambiar el mundo son los que lo logran",
            "La rutina es el cementerio del genio",
            "La inspiración existe, pero debe encontrarte trabajando",
            "Crea más de lo que consumes",
            "La mejor manera de predecir el futuro es creándolo",
            "Los límites solo existen si los aceptas",
            "La magia ocurre fuera de tu zona de confort",
            "Rompe las reglas pero domina primero el juego",
            "Las tormentas hacen más fuertes a los árboles",
            "Caer está permitido, quedarse en el suelo no",
            "La vida no es esperar a que pase la tormenta, es aprender a bailar bajo la lluvia",
            "Las cicatrices son tatuajes de victoria",
            "El fracaso no es lo contrario al éxito, es parte de él",
            "Cuando el mundo entero parezca oscuro, sé tu propia luz",
            "Las piedras en el camino? Guárdalas para construir tu castillo",
            "La adversidad revela el verdadero carácter",
            "Si el plan no funciona, cambia el plan pero no la meta",
            "La resistencia se construye cargando peso, no evitándolo",
            "El propósito es el motor del alma",
            "Encuentra tu fuego y nadie podrá apagarlo",
            "La pasión convierte lo ordinario en extraordinario",
            "No busques trabajo, busca misión",
            "El dinero sigue a la pasión, no al revés",
            "Tu vocación debería hacerte sentir vivo, no solo pagar cuentas",
            "El mundo necesita lo que solo tú puedes aportar",
            "La verdadera riqueza es levantarte cada día con propósito",
            "No midas tu vida en años, mídela en aportaciones",
            "El legado más grande es vivir con autenticidad",
            "El miedo es temporal, el arrepentimiento es para siempre",
            "La excelencia no es un acto, es un hábito",
            "Tus decisiones de hoy escriben tu historia de mañana",
            "La autodisciplina es el secreto mejor guardado del éxito",
            "Nunca subestimes el poder de un pequeño paso constante",
            "La vida es como una cámara: enfócate en lo importante",
            "El conocimiento te da poder, la acción te da resultados",
            "Los obstáculos son esas cosas espantosas que ves cuando apartas los ojos de tu meta",
            "La verdadera educación es sacar a relucir lo mejor de ti",
            "La consistencia convierte lo ordinario en extraordinario"
    };

    private final Random random = new Random();

    public String obtenerFraseAleatoria() {
        int indice = random.nextInt(frases.length);
        return frases[indice];
    }

}
